# this is only used by dvc

Path: config/config.yaml
Experiment_name: 
  name: Dncnn # change experiment name for each experiment 

Default_device:
  device: cuda


Train_config: 
  device: cuda
  batch_size: 25
  epochs: 1
  lr: 0.001
  # lr_scheduler: True
  lr_scheduler: 
    mode: 'min'
    factor: 0.1
    patience: 20
    verbose: True

  optimizer: adam
  loss : mse




# change dataset directories
Train_DL_config:
  train_hr_dir: /media/aps/D826F6E026F6BE96/RnD/dataset/train/hr/
  batch_size: 25
  num_workers: 4
  shuffle: True
  transform: True
  

Val_DL_config:
  val_hr_dir: /media/aps/D826F6E026F6BE96/RnD/dataset/val/hr/
  batch_size: 16
  num_workers: 4
  shuffle: False
  transform: True
  random_blur: False 


Test_DL_config: 
  # setting to val as test dir is corrupted in local drive
  test_hr_dir: /media/aps/D826F6E026F6BE96/RnD/dataset/val/hr/
  batch_size: 32
  num_workers: 4
  shuffle: False
  transform: True
  random_blur: True


Paths : 
  dataset : /media/aps/D826F6E026F6BE96/RnD/dataset/
  log_dir : /media/aps/D826F6E026F6BE96/RnD/mlflow/DncnnV/logs/
  model_ckpt: /media/aps/D826F6E026F6BE96/RnD/mlflow/DncnnV/artifact/model_ckpt/
  figs: /media/aps/D826F6E026F6BE96/RnD/mlflow/DncnnV/figs

# setting t1 image_size to 256 clashes with unet, works with DnCnnv
Transform:
  t1 :
    p: 1
    image_size: 512
  t2 :
    p: 1
    image_size: 256
    blur_limit: 
      min: 3
      max: 7
  normalization:
    mean :
      - 0
      - 0
      - 0
    std :
      - 1.0
      - 1.0
      - 1.0
  seed: 42

Test_config: 
  model_path: /media/aps/D826F6E026F6BE96/RnD/mlflow/DncnnV/artifact/model_ckpt/Dncnn_best_2024-09-01-17-05-29.pth



model_config : 
  model_name: Dncnn
  in_channels: 3
  out_channels: 3
  start_channels: 64
  depth: 12
  up_scale: 1
  weight_initilization: True # weight initilization don't improve the performance val loss stack at 70.0
  mood: test


seg_model_config : 
  model_name: Unet
  backbone: resnet34 
  weights: imagenet 
  in_channels: 3 
  out_channels: 3 


evaluation_tracker : 
  model_name: Dncnn
  model_path: /media/aps/D826F6E026F6BE96/RnD/mlflow/DncnnV/artifact/model_ckpt/Dncnn_best_2024-09-01-17-05-29.pth
  test_dir: /media/aps/D826F6E026F6BE96/RnD/dataset/test/hr/
  batch_size: 32
  device: cuda


Prediction_config : 
  model_name: Dncnn
  model_path: /media/aps/D826F6E026F6BE96/RnD/mlflow/DncnnV/artifact/model_ckpt/Dncnn_best_2024-09-01-17-05-29.pth
  transform : 
    p: 1
    image_size: 256
    normalization:
      mean :
        - 0.485
        - 0.456
        - 0.406
      std :
        - 0.229
        - 0.224
        - 0.225


  
