#Path: config/config.yaml
Train_config: 
  batch_size: 32
  epochs: 200
  lr: 0.001
  lr_sheduler: False
  lr_scheduler: 
    mode: 'min'
    factor: 0.1
    patience: 20
    verbose: True

  optimizer: adam
  loss : mse


Train_DL_config:
  train_hr_dir: G:\muzzle\train\hr/
  batch_size: 32
  num_workers: 4
  shuffle: True
  transform: True

Val_DL_config:
  val_hr_dir: G:\muzzle\val\hr/
  batch_size: 16
  num_workers: 4
  shuffle: False
  transform: True 


Test_DL_config: 
  test_hr_dir: G:\muzzle\test\hr/
  batch_size: 32
  num_workers: 4
  shuffle: False
  transform: True

Paths : 
  dataset : C:\Users\Amzad\Desktop\Dncnn\dataset/
  log_dir : C:\Users\Amzad\Desktop\Dncnn\logs/
  model_ckpt: C:\Users\Amzad\Desktop\Dncnn\artifact\model_ckpt/
  figs: C:\Users\Amzad\Desktop\Dncnn\figs/

Transform:
  t1 :
    p: 1
    image_size: 256
  t2 :
    p: 1
    image_size: 128
    blur_limit: 
      min: 3
      max: 7
  normalization:
    mean :
      - 0.485
      - 0.456
      - 0.406
    std :
      - 0.229
      - 0.224
      - 0.225
  seed: 42

Test_config: 
  model_path: C:\Users\Amzad\Desktop\Dncnn\artifact\model_ckpt\Dncnn_best_2024-01-02-17-03-27.pth



model_config : 
  in_channels: 3
  out_channels: 3
  start_channels: 64
  depth: 17
  up_scale: 1
  weight_initilization: False # weight initilization don't improve the performance val loss stack at 70.0







  
